/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kontaktlista;

import java.sql.SQLException;
import java.sql.ResultSet;
/**
 *
 * @author isawe04
 */
public class JFrameKontaktLista extends javax.swing.JFrame {
    DbManager db = new DbManager();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameKontaktLista.class.getName());
    
    /**
     * Creates new form JFrameKontaktLista
     */
    public JFrameKontaktLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        förnamn1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        förnamn2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblFörnamn = new javax.swing.JLabel();
        txfFörnamn = new javax.swing.JTextField();
        txfEfternamn = new javax.swing.JTextField();
        lblEfternamn = new javax.swing.JLabel();
        txfTelefon = new javax.swing.JTextField();
        lblTelefon = new javax.swing.JLabel();
        btnLäggTill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaLista = new javax.swing.JTextArea();
        lblLista = new javax.swing.JLabel();
        rBtnFörnamnFörst = new javax.swing.JRadioButton();
        rBtnEfternamnFörst = new javax.swing.JRadioButton();
        btnSpara = new javax.swing.JButton();
        btnHämta = new javax.swing.JButton();
        btnRaderaKontakt = new javax.swing.JButton();
        txfRaderaKontaktId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        förnamn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                förnamn1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Förnamn");

        förnamn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                förnamn2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Förnamn");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFörnamn.setText("Förnamn");

        txfFörnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfFörnamnActionPerformed(evt);
            }
        });

        txfEfternamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEfternamnActionPerformed(evt);
            }
        });

        lblEfternamn.setText("Efternamn");

        txfTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfTelefonActionPerformed(evt);
            }
        });

        lblTelefon.setText("Telefon");

        btnLäggTill.setText("Lägg till");
        btnLäggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLäggTillActionPerformed(evt);
            }
        });

        txaLista.setEditable(false);
        txaLista.setColumns(20);
        txaLista.setRows(5);
        jScrollPane1.setViewportView(txaLista);

        lblLista.setText("Lista");

        buttonGroup1.add(rBtnFörnamnFörst);
        rBtnFörnamnFörst.setSelected(true);
        rBtnFörnamnFörst.setText("Förnamn först");
        rBtnFörnamnFörst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnFörnamnFörstActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBtnEfternamnFörst);
        rBtnEfternamnFörst.setText("Efternamn först");
        rBtnEfternamnFörst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnEfternamnFörstActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnHämta.setText("Hämta");
        btnHämta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHämtaActionPerformed(evt);
            }
        });

        btnRaderaKontakt.setText("Radera kontakt");
        btnRaderaKontakt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaKontaktActionPerformed(evt);
            }
        });

        jLabel1.setText("Kontakt id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFörnamn)
                            .addComponent(lblTelefon))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(lblEfternamn)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfEfternamn, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnLäggTill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rBtnFörnamnFörst)
                                .addGap(18, 18, 18)
                                .addComponent(rBtnEfternamnFörst))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblLista)
                                .addGap(18, 18, 18)
                                .addComponent(btnSpara)
                                .addGap(18, 18, 18)
                                .addComponent(btnHämta)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfRaderaKontaktId)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRaderaKontakt)))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFörnamn)
                    .addComponent(txfFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEfternamn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(txfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLäggTill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLista)
                    .addComponent(btnSpara)
                    .addComponent(btnHämta)
                    .addComponent(btnRaderaKontakt)
                    .addComponent(txfRaderaKontaktId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnFörnamnFörst)
                    .addComponent(rBtnEfternamnFörst))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfFörnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfFörnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfFörnamnActionPerformed

    private void förnamn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_förnamn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_förnamn1ActionPerformed

    private void txfEfternamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEfternamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEfternamnActionPerformed

    private void förnamn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_förnamn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_förnamn2ActionPerformed

    private void txfTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfTelefonActionPerformed

    private void btnLäggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLäggTillActionPerformed
        String förnamn = txfFörnamn.getText();
        String efternamn = txfEfternamn.getText();
        String telefon = txfTelefon.getText();
        if(!förnamn.isBlank() && !efternamn.isBlank()){
            Kontakt kon = new Kontakt(förnamn, efternamn, telefon);
            db.insert(kon);
        }
        if(this.rBtnFörnamnFörst.isSelected()){
            skrivUtFörnamn();
        }
        else{
            skrivUtEfternamn();
        }
        //Kontakt kon = new Kontakt(förnamn, efternamn, telefon);
        //konLista.add(kon);
        /*if(rBtnFörnamnFörst.isSelected()){
        txaLista.setText("");
        for (int i = 0; i < konLista.size(); i++) {
            txaLista.append((konLista.get(i).getFörnamn()+"\t"+konLista.get(i).getEfternamn()+"\t"+konLista.get(i).getTelefonnummer()+"\n"));
        }
        }
        else{
         for (int i = 0; i < konLista.size(); i++) {
            txaLista.append((konLista.get(i).getEfternamn()+"\t"+konLista.get(i).getFörnamn()+"\t"+konLista.get(i).getTelefonnummer()+"\n"));
        } 
        }
        txfFörnamn.setText("");
        txfEfternamn.setText("");
        txfTelefon.setText("");
        */
    }//GEN-LAST:event_btnLäggTillActionPerformed

    private void rBtnFörnamnFörstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnFörnamnFörstActionPerformed
        txaLista.setText("");
    }//GEN-LAST:event_rBtnFörnamnFörstActionPerformed

    private void rBtnEfternamnFörstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnEfternamnFörstActionPerformed
        txaLista.setText("");
    }//GEN-LAST:event_rBtnEfternamnFörstActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        //Fil.saveToFile(konLista);
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnHämtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHämtaActionPerformed
        if(rBtnFörnamnFörst.isSelected()){
        txaLista.setText("");
        ResultSet rs = db.getAllData();
        try {
                while (rs.next()) {
                    this.txaLista.append(rs.getInt("kontaktid") + "\t"
                            + rs.getString("firstname") + "\t"
                            + rs.getString("lastname") + "\t"
                            + rs.getString("phonenumber") + "\n");
                }
            } catch (SQLException ex) {
                System.out.println("Ingen data.");
            }
        }else{
            txaLista.setText("");
        ResultSet rs = db.getAllData();
        try {
                while (rs.next()) {
                    this.txaLista.append(rs.getInt("kontaktid") + "\t"
                            + rs.getString("lastname") + "\t"
                            + rs.getString("firstname") + "\t"
                            + rs.getString("phonenumber") + "\n");
                }
            } catch (SQLException ex) {
                System.out.println("Ingen data.");
            }
        }
    }//GEN-LAST:event_btnHämtaActionPerformed

    private void btnRaderaKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaKontaktActionPerformed
        try{
            String raderaKontaktId = txfRaderaKontaktId.getText();
            if(!raderaKontaktId.isBlank()){
                int id = Integer.parseInt(raderaKontaktId);
                db.raderaKontakt(id);
                txfRaderaKontaktId.setText("");
                if (this.rBtnFörnamnFörst.isSelected()) {
                skrivUtFörnamn();
                } else {
                skrivUtEfternamn();
                }
            }
        }catch(NumberFormatException e){
            System.out.println("Fel: Ange ett ID nummer.");
         }
        
    }//GEN-LAST:event_btnRaderaKontaktActionPerformed

    private void skrivUtFörnamn(){
        this.txaLista.setText("");
        ResultSet rs = db.getAllData();
        if (rs != null) {
            try {
                while (rs.next()) {
                    this.txaLista.append(rs.getInt("kontaktid") + "\t"
                            + rs.getString("firstname") + "\t"
                            + rs.getString("lastname") + "\t"
                            + rs.getString("phonenumber") + "\n");
                }
            } catch (SQLException ex) {
                System.out.println("Ingen data.");
            }
        } else {
            System.out.println("Ingen data från databasen, kontrollera anslutningen.");
        }

    }
    private void skrivUtEfternamn(){
        this.txaLista.setText("");
        ResultSet rs = db.getAllData();
        if (rs != null) {
            try {
                while (rs.next()) {
                    this.txaLista.append(rs.getInt("kontaktid") + "\t"
                            + rs.getString("lastname") + "\t"
                            + rs.getString("firstname") + "\t"
                            + rs.getString("phonenumber") + "\n");
                }
            } catch (SQLException ex) {
                System.out.println("Ingen data.");
            }
        } else {
            System.out.println("Ingen data från databasen, kontrollera anslutningen.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameKontaktLista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHämta;
    private javax.swing.JButton btnLäggTill;
    private javax.swing.JButton btnRaderaKontakt;
    private javax.swing.JButton btnSpara;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField förnamn1;
    private javax.swing.JTextField förnamn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblFörnamn;
    private javax.swing.JLabel lblLista;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JRadioButton rBtnEfternamnFörst;
    private javax.swing.JRadioButton rBtnFörnamnFörst;
    private javax.swing.JTextArea txaLista;
    private javax.swing.JTextField txfEfternamn;
    private javax.swing.JTextField txfFörnamn;
    private javax.swing.JTextField txfRaderaKontaktId;
    private javax.swing.JTextField txfTelefon;
    // End of variables declaration//GEN-END:variables
}
